package com.todaynews.ssm2.bean;

import java.util.Date;

public class Conversation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.id
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.user_id
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.friend_id
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    private Integer friendId;

    //会话对象
    private User friend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.earliest_message_date
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    private Date earliestMessageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.state
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.message_count
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    private Integer messageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.unread_count
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    private Integer unreadCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.latest_message_content
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    private String latestMessageContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.id
     *
     * @return the value of conversation.id
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.id
     *
     * @param id the value for conversation.id
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.user_id
     *
     * @return the value of conversation.user_id
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.user_id
     *
     * @param userId the value for conversation.user_id
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.friend_id
     *
     * @return the value of conversation.friend_id
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.friend_id
     *
     * @param friendId the value for conversation.friend_id
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.earliest_message_date
     *
     * @return the value of conversation.earliest_message_date
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public Date getEarliestMessageDate() {
        return earliestMessageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.earliest_message_date
     *
     * @param earliestMessageDate the value for conversation.earliest_message_date
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public void setEarliestMessageDate(Date earliestMessageDate) {
        this.earliestMessageDate = earliestMessageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.state
     *
     * @return the value of conversation.state
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.state
     *
     * @param state the value for conversation.state
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.message_count
     *
     * @return the value of conversation.message_count
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public Integer getMessageCount() {
        return messageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.message_count
     *
     * @param messageCount the value for conversation.message_count
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public void setMessageCount(Integer messageCount) {
        this.messageCount = messageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.unread_count
     *
     * @return the value of conversation.unread_count
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public Integer getUnreadCount() {
        return unreadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.unread_count
     *
     * @param unreadCount the value for conversation.unread_count
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public void setUnreadCount(Integer unreadCount) {
        this.unreadCount = unreadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.latest_message_content
     *
     * @return the value of conversation.latest_message_content
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public String getLatestMessageContent() {
        return latestMessageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.latest_message_content
     *
     * @param latestMessageContent the value for conversation.latest_message_content
     *
     * @mbg.generated Sat Apr 21 22:38:39 CST 2018
     */
    public void setLatestMessageContent(String latestMessageContent) {
        this.latestMessageContent = latestMessageContent == null ? null : latestMessageContent.trim();
    }

    public User getFriend() {
        return friend;
    }

    public void setFriend(User friend) {
        this.friend = friend;
    }
}