package com.todaynews.ssm2.bean;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.user_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.friend_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    private Integer friendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.from_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    private Integer fromId;

    //发送者
    private User sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.to_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    private Integer toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.created_date
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.state
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.conversation_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    private Integer conversationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_id
     *
     * @return the value of message.user_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.user_id
     *
     * @param userId the value for message.user_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.friend_id
     *
     * @return the value of message.friend_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.friend_id
     *
     * @param friendId the value for message.friend_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.from_id
     *
     * @return the value of message.from_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.from_id
     *
     * @param fromId the value for message.from_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.to_id
     *
     * @return the value of message.to_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.to_id
     *
     * @param toId the value for message.to_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.created_date
     *
     * @return the value of message.created_date
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.created_date
     *
     * @param createdDate the value for message.created_date
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.state
     *
     * @return the value of message.state
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.state
     *
     * @param state the value for message.state
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.conversation_id
     *
     * @return the value of message.conversation_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public Integer getConversationId() {
        return conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.conversation_id
     *
     * @param conversationId the value for message.conversation_id
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public void setConversationId(Integer conversationId) {
        this.conversationId = conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Sat Apr 21 21:52:43 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public User getSender() {
        return sender;
    }

    public void setSender(User sender) {
        this.sender = sender;
    }
}