package com.todaynews.ssm2.bean;

import java.util.Date;
import java.util.List;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_date
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.image
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.like_count
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.link
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.comment_count
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.state
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    private Integer state;

    //新闻提供者的id
    private Integer uid;

    //新闻提供者
    private User user;

    //评论
    List<Comment> comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.create_date
     *
     * @return the value of news.create_date
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.create_date
     *
     * @param createDate the value for news.create_date
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.image
     *
     * @return the value of news.image
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.image
     *
     * @param image the value for news.image
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.like_count
     *
     * @return the value of news.like_count
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.like_count
     *
     * @param likeCount the value for news.like_count
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.link
     *
     * @return the value of news.link
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.link
     *
     * @param link the value for news.link
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.comment_count
     *
     * @return the value of news.comment_count
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.comment_count
     *
     * @param commentCount the value for news.comment_count
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.state
     *
     * @return the value of news.state
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.state
     *
     * @param state the value for news.state
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getUid() {
        return uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<Comment> getComments() {
        return comments;
    }

    public void setComments(List<Comment> comments) {
        this.comments = comments;
    }

    @Override
    public String toString() {
        return "News{" +
                "id=" + id +
                ", createDate=" + createDate +
                ", image='" + image + '\'' +
                ", title='" + title + '\'' +
                ", likeCount=" + likeCount +
                ", link='" + link + '\'' +
                ", commentCount=" + commentCount +
                ", state=" + state +
                ", uid=" + uid +
                ", user=" + user +
                ", comments=" + comments +
                '}';
    }
}