package com.todaynews.ssm2.dao;

import com.todaynews.ssm2.bean.Comment;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sat Apr 21 00:10:51 CST 2018
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sat Apr 21 00:10:51 CST 2018
     */
    int updateByPrimaryKey(Comment record);

    List<Comment> findCommentByNewsId();

    @Insert("insert into comment values(null, #{createdDate}, #{content}, 0, #{newsId}, #{uid});")
    int insertComment(Comment comment);

}