package com.todaynews.ssm2.dao;

import com.todaynews.ssm2.bean.Conversation;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.util.List;

@Mapper
public interface ConversationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sat Apr 21 21:45:30 CST 2018
     */
    int updateByPrimaryKeySelective(Conversation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Sat Apr 21 21:45:30 CST 2018
     */
    int updateByPrimaryKey(Conversation record);

    List<Conversation> findAllValidConversationByUserId(Integer userId);

    Conversation findConversationByUserIdAndFriendId(@Param("userId") Integer userId,
                                                     @Param("friendId") Integer friendId);

    @Insert("insert into conversation values(null, #{userId}, #{friendId}, " +
            "#{earliestMessageDate}, #{state}, #{messageCount}, #{unreadCount}, #{latestMessageContent});")
    int insertConversation(Conversation conversation);

    @Update("update conversation set unread_count = 0 where id = #{conversationId};")
    int updateUnreadCountById(int conversationId);
}