package com.todaynews.ssm2.dao;

import com.todaynews.ssm2.bean.Message;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.util.List;

@Mapper
public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sat Apr 21 17:09:48 CST 2018
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sat Apr 21 17:09:48 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sat Apr 21 17:09:48 CST 2018
     */
    int updateByPrimaryKey(Message record);

    @Insert("insert into message values(null, #{userId}, #{friendId}," +
            " #{fromId}, #{toId}, #{content}, #{createdDate}, #{state}, #{conversationId});")
    int insertMessage(Message message);

    List<Message> findAllMessageByUserIdAndConversationId(@Param("userId") Integer userId,
                                                          @Param("conversationId") int conversationId);

    @Update("update message set state = #{state} where id = #{id};")
    int updateStateById(Message message);
}