package com.todaynews.ssm2.dao;

import com.todaynews.ssm2.bean.News;
import org.apache.ibatis.annotations.*;

import java.util.List;

@Mapper
public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Fri Apr 20 10:49:29 CST 2018
     */
    int updateByPrimaryKey(News record);

    //@Insert("insert into news values(null, #{createDate}, #{image}, #{title}, #{likeCount}, #{link}, #{commentCount}, #{state}, #{uid})")
    @Insert("insert into news values(null, #{createDate}, #{image}, #{title}, 0, #{link}, 0, 0, #{uid})")
    int insertNews(News news);

    //@Select("select * from news where state = 0")
    List<News> findAllNews();

    @Update("update news set like_count = like_count + 1 where id = #{id} and state = 0;")
    int addLikeCountByNewsId(int id);

    News findNewsById(int id);

    @Update("update news set comment_count = comment_count + 1 where id = #{id} and state = 0;")
    int addCommentCountById(Integer id);

    @Update("update news set like_count = #{likeCount} where id = #{newsId} and state = 0;")
    int updateLikeCountByNewsId(@Param("newsId") Integer newsId,
                                @Param("likeCount") int likeCount);

    @Select("select uid from news where id = #{newsId};")
    int findOwnerIdByNewsId(int newsId);
}